### ISSUE TITLE
Ability to fetch section in JSON format

### ISSUE THREAD

**Issue by parisk** [mozilla/kuma#2026]
Currently, its impossible to combine the section parameter with the JSON metadata resource (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Location?Properties$json renders HTML instead of JSON).

Such a feature would be really useful to developers seeking to parse MDN, or any other web site that uses Kuma.

I will fork that repo and do a pull request for that.

**Comment by mbehzad** [comment]
any updates on this? on the linked bugzilla bug the last comment says "bug reporting has now moved to GitHub"

**Comment by peterbe** [comment]
> any updates on this? on the linked bugzilla bug the last comment says "bug reporting has now moved to GitHub"

We're working on moving all of MDNs content into `git`. It'll be unstructured. But [yari](https://github.com/mdn/yari) is the build tool that (attempts to) transforms that unstructured content into JSON so it can build a static site.
