### ISSUE TITLE
**DO NOT ADD ISSUES HERE**

### ISSUE THREAD

**Issue by groovecoder** [mozilla/kuma#2941]
MDN's issue & bug tracking is done in bugzilla. Please use our bugzilla form to create issues/bugs:

https://bugzilla.mozilla.org/form.mdn

(The GitHub issues are enabled because bugzilla bugs link back to some old issues.)

Thanks,
MDN dev team

**Comment by anaran** [comment]
:+1: It's always good to see it explained _why_ things are set up a certain way.

**Comment by candiigurl2go** [comment]
fucking gay, i am being hacked somehow and i have no idea what i am doing and i end up always on this site until things get changed into another language or locks me out. I am a single mom with a 3 year old daughter with both of our idenitys stolen from us and caused plenty of problems please help me!!when i try to explain to anyone what is going on here i am looked at like im crazy! please and thanks.

**Comment by mahdiameri** [comment]
Hello Thank you very much

**Comment by dijonkitchen** [comment]
FYI, it might be easier to just disable issues on this repo and just note in the `CONTRIBUTING.md`.

**Comment by jwhitlock** [comment]
Good idea @dijonkitchen. Not many people read the ``CONTRIBUTING.md``, but it is linked in the info bar when you open an issue. It should reflect current practices.

My reading of the [GitHub page on disabling issues](https://help.github.com/articles/disabling-issues/) is that disabling it will not delete the data, but will make it impossible to get to old issues. I'm reluctant to lose those conversations. I may do some research in a test repository to see what happens when you disable issues on a project that was using them.

**Comment by chaficnajjar** [comment]
> https://bugzilla.mozilla.org/form.mdn

@groovecoder The link is broken. That's what I see when opening the page:

> ### Permission Denied
> Sorry, either the product Mozilla Developer Network does not exist or you aren't authorized to enter a bug into it.

**Comment by jwhitlock** [comment]
@chaficnajjar, we recently [changed the product name in Bugzilla](https://discourse.mozilla.org/t/changing-mozilla-developer-network-component-to-developer-mozilla-org-in-bugzilla/25542?u=jwhitlock) from **Mozilla Developer Network** to **developer.mozilla.org**. This [broke ``form.mdn``](https://bugzilla.mozilla.org/show_bug.cgi?id=1439693), but [an update](https://github.com/mozilla-bteam/bmo/pull/406) has been approved and merged.

Until that is deployed, you can use the guided bug entry form:

https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes|developer.mozilla.org

**Comment by jwhitlock** [comment]
We're trying [ZenHub](https://www.zenhub.com/) for project planning. We may start using issues if required by the new workflow, or we may be able to add the issues, milestones, etc. at https://github.com/mdn/sprints. Bugzilla, and [form.mdn](https://bugzilla.mozilla.org/form.mdn), is still the preferred place for bugs and feature requests.

**Comment by FranklinYu** [comment]
We can prevent user from creating issue by adding an [issue template](https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates) pointing user to Bugzilla. I have seen other repository doing this.

**Comment by ExE-Boss** [comment]
Well, this seems to be no longer accurate, given [bug 1573928](https://bugzilla.mozilla.org/show_bug.cgi?id=1573928#c1) and #5642.

**Comment by peterbe** [comment]
@ExE-Boss you're right!

The bug that "marked the end of Bugzilla for kuma" was: https://bugzilla.mozilla.org/show_bug.cgi?id=1573155
