### ISSUE TITLE
Random "t" above summary header

### ISSUE THREAD

**Issue by coreysnyder04** [mozilla/kuma#3082]
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

On this page there is a random "t" character under the summary header at the top of the main section

**Comment by groovecoder** [comment]
Hi @coreysnyder04, thanks for the report. We don't use these GitHub issues to track bugs anymore. (see https://github.com/mozilla/kuma/issues/2941)

In this case, I think the bug is a content issue. Can you fix it yourself by editing the page?
