### ISSUE TITLE
Array.prototype.reduce   Description section unclear to new programmers

### ISSUE THREAD

**Issue by eshimel** [mozilla/kuma#3612]
I've been working my way through this entry in the MDN with a group of programmers new to JavaScript, and we agree that number 1. of the Description section is a little unclear.  It currently states:

1.the initial value (or value from the previous callback call)

I suggest that it be updated to:
1. the initial value (or returning value from the previous callback call)
Adding "returning" to the statement makes it easier to understand how the function is using the callback call.

Thank you!

**Comment by jwhitlock** [comment]
@eshimel - Thanks for your suggestion. It is valuable to get feedback from people first learning these concepts, and I think you should feel free to change things to make them more understandable.

MDN is a wiki, and the way to make your suggestion is to edit the page:

1. Create an account (see https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Create_an_MDN_account)
2. Go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
3. Click the "Edit" button
4. Make your change
5. Save it

If you have other questions about contributing to MDN, please see https://developer.mozilla.org/en-US/docs/MDN/Getting_started

This github repo is for Kuma, the code that runs the wiki, not the content in the wiki.  As mentioned in bug  #2941, Kuma bugs should be filed in bugzilla.

**Comment by eshimel** [comment]
Thank you!  the update has been made!
