### ISSUE TITLE
Pluralize

### ISSUE THREAD

**Issue by SafaAlfulaij** [mozilla/kuma#4651]
https://github.com/mozilla/kuma/blob/27b77dc0828de69ad77e134e17334cbdf7f9f8d4/kuma/attachments/models.py#L140

**Comment by SafaAlfulaij** [comment]
https://github.com/mozilla/kuma/blob/27b77dc0828de69ad77e134e17334cbdf7f9f8d4/kuma/core/form_fields.py#L57

_Yes I know this isn't used. I'll just put them here as it's eaiser to just get a direct link._

**Comment by jwhitlock** [comment]
Feel free to file in Bugzilla: https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20Developer%20Network&component=General
