### ISSUE TITLE
Determine the need for ZillaSlab Regular

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5617]
Currently, we are serving the ZillaSlab Regular font face for roughly two headings per page. The potential performance gain from reducing our custom font dependance to only one outweigh the small aesthetic benefit of the custom font.

## Tasks

- [x] Determine whether there are any other uses of the Regular font face
- [ ] If not, remove the dependance and use Arial for the headings

**Comment by schalkneethling** [comment]
After doing another pass, the Regular version of the font is used in a number of places, especially on the Learn portion of the site. For the moment it is not going to be possible to remove the need for ZillaSlab Regular.

**Comment by peterbe** [comment]
Separate issue about adding ZillaSlab-Regular as a...
```
<link rel="preload" href="/ZillaSlab-Regular.subset.e96c15f68c68.woff2" as="font" type="font/woff2" crossorigin />
```
...tag.
Just like we're doing with the ZillaSlab-Bold already.

**Comment by schalkneethling** [comment]
> Separate issue about adding ZillaSlab-Regular as a...
> 
> ```
> <link rel="preload" href="/ZillaSlab-Regular.subset.e96c15f68c68.woff2" as="font" type="font/woff2" crossorigin />
> ```
> 
> ...tag.
> Just like we're doing with the ZillaSlab-Bold already.

Yup, yup. That is the logical next step.
