### ISSUE TITLE
Convert newsletter signup form to React Land

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5641]
While working on converting the [footer for docs pages](https://github.com/mozilla/kuma/issues/5640) to React I realized that we first need to convert the newsletter signup form.

This will only be applied to the `docs` pages and not the landing page currently. The component should be coded in a way that will allow us to reuse it easily in different places such as on the landing page, and later on the profile pages.

**Comment by schalkneethling** [comment]
@escattone @peterbe Do we currently have a way to get at the `settings` that we sometimes use inside Jinja templates inside the new React front-end? The newsletter uses the following:

```
{% if settings.NEWSLETTER and settings.NEWSLETTER_ARTICLE %}
<div class="center">
  <div class="newsletter-box">
    {% include "includes/newsletter.html" %}
  </div>
</div>
{% endif %}
```

**Comment by escattone** [comment]
@schalkneethling No, but we could add whatever settings we need [here](https://github.com/mozilla/kuma/blob/a3466efa445036d8f44b2a75c208627fc8d08822/kuma/wiki/templatetags/ssr.py#L41), and they would be available within SSR service (via the `data` argument to the `ssr` function -- see https://github.com/mozilla/kuma/blob/a3466efa445036d8f44b2a75c208627fc8d08822/kuma/javascript/src/ssr.jsx#L12 ) as well as via the `window._react_data` we use for hydration.

**Comment by schalkneethling** [comment]
Turns out keeping the two newsletter related settings will not be trivial so, I spoke to @atopal on Slack and also did some digging to see how the code is used. Here is what I have found.

First of all, it is defined here https://github.com/mozilla/kuma/blob/master/kuma/settings/common.py#L1862 and only here. I had a look in the admin and there is nothing under `constance` or any other setting that is admin administrable.

Looking at how this is used in the templates(which is the only place it is used), it is clear that this was used as a means to:

1.  completely turn off showing the newsletter signup form
2. turn it off for article pages

For example, in `homepage.html`

```
{% if settings.NEWSLETTER %}
<div class="column-callout callout-newsletter">
    {% include "includes/newsletter.html" %}
</div>
```

And then in `document.html`

```
{% if settings.NEWSLETTER and settings.NEWSLETTER_ARTICLE %}
  <div class="newsletter-box">
    {% include "includes/newsletter.html" %}
  </div>
{% endif %}
```

And then in `user_edit.html`

```
{% if settings.NEWSLETTER %}
{% include "includes/newsletter.html" %}
<h3>Unsubscribe</h3>
<p><a href="https://www.mozilla.org/en-US/newsletter/recovery/">{{ _('Manage your Mozilla Newsletter Subscriptions.') }}</a></p>
{% endif %}
```

Which is kinda strange because, if you have subscribed and we then turn newsletter off, you won't be able to unsubscribe ;p

I passed this information on to @atopal and the conclusion was:

> @sneethling as long it won’t break anything, we will do without the ability from here on.

With that, I am going to forgo porting this part of the newsletter.

**Comment by peterbe** [comment]
> we will do without the ability from here on.

What ability?

First of all, it's odd that it's not done like this:
```python
NEWSLETTER = config('NEWSLETTER', cast=bool, default=True)
```
How realistic is it even that you'd want to disable newsletter sign up? What's the point of protecting it behind a flag at all? If we ever decide to remove the signup form, we'd make a pull request to delete all the code for it. 

Other than that, the simplest thing would be to take heed from @escattone 's advice above about the data shipped to ssr. 

There isn't much ways around that. The configuration lives in Python `settings/common.py` and the only way that can end up in React-land is via serialized JSON.

**Comment by peterbe** [comment]
By the way, I don't think it's that odd that `'Manage your Mozilla Newsletter Subscriptions.` would go away if the subscription object goes away. Gut tells me 99.9% of people would use the "Unsubscribe" link in the newsletters if they'd want to un-subscribe.

**Comment by schalkneethling** [comment]
> By the way, I don't think it's that odd that `'Manage your Mozilla Newsletter Subscriptions.` would go away if the subscription object goes away. Gut tells me 99.9% of people would use the "Unsubscribe" link in the newsletters if they'd want to un-subscribe.

Fair enough ;p

**Comment by schalkneethling** [comment]
> There isn't much ways around that. The configuration lives in Python `settings/common.py` and the only way that can end up in React-land is via serialized JSON.

The effort in keeping it is simply not worth it. Since I have joined this team(more than 2 years now) we have never shut of newsletter subscription in any form.

**Comment by atopal** [comment]
> > we will do without the ability from here on.
> 
> What ability?

The ability to turn the newsletter off on specific article pages.

**Comment by schalkneethling** [comment]
> > > we will do without the ability from here on.
> > 
> > 
> > What ability?
> 
> The ability to turn the newsletter off on specific article pages.

Well, not specific article pages but just article pages in general. So it added the ability to turn the newsletter of completely or, to turn it off only on article pages i.e. it will only show on the landing page and the user edit page.
