### ISSUE TITLE
Double top border for collapsible <h2> text on mobile

### ISSUE THREAD

**Issue by tobinmori** [mozilla/kuma#5642]
This has recently (within the last month) started occurring on mobile.
![attachment](https://user-images.githubusercontent.com/1248442/63044914-3fbcee00-be9d-11e9-8fbc-f0314a7f4d41.png)

**Comment by schalkneethling** [comment]
Fixed in https://github.com/mozilla/kuma/pull/5643

**Comment by peterbe** [comment]
@ExE-Boss Can you confirm that this has been solved on developer.allizom.org?

**Comment by ExE-Boss** [comment]
I can confirm that this has now been fixed.
