### ISSUE TITLE
Set up GitHub issue template

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5646]
Now that we're filing more issues here instead of Bugzilla we should set up some really decent GitHub templates. Let's only worry about Issues for now. 

See:
https://help.github.com/en/articles/about-issue-and-pull-request-templates

I like the idea of multiple issue templates. 
But I also think we should find a good balance that works for drive-by bug/feature reporters AND for core developers who don't want to fill out a cumbersome questionnaire.

**Comment by peterbe** [comment]
@tobinmori Wanna assign this to yourself and have the bikeshedding unleashed on your PR?

**Comment by tobinmori** [comment]
this was done. closing this.
