### ISSUE TITLE
Change "Report a bug" link in "Feedback" menu to GitHub

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5647]
Now that we're switching to using GitHub issues, we should redirect people filing bugs to here instead. 

It might be out of scope but I've never liked that it says "Report a bug" but typing "Report a bug/feature" isn't great either. Perhaps we can consider "Report an issue".

**Comment by schalkneethling** [comment]
Opening this up as a good first issue. Perhaps @ankiiitraj will be interested in this one?

**Comment by ankiiitraj** [comment]
Thank You @schalkneethling . I am interested in this fixing this issue as my first contribution. Please guide me in this issue.

**Comment by schalkneethling** [comment]
> Thank You @schalkneethling . I am interested in this fixing this issue as my first contribution. Please guide me in this issue.

Great! The first step it to get Kuma running locally on your machine. If you have not already done so, please [follow the instructions here](https://kuma.readthedocs.io/en/latest/installation.html) and let me know should you run into any trouble.

**Comment by ExE-Boss** [comment]
I was about to do this myself, but then I noticed that @ankiiitraj has already signed up for this, so I’ll at least post my findings.

<details>
<summary>Occurrences of <code>https://bugzilla.mozilla.org/form.mdn</code> in the kuma codebase:</summary>

https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/contribute.json#L22-L27 https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/jinja2/500.html#L34-L36 https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/jinja2/includes/header-main-nav.html#L68-L70 https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/kuma/javascript/src/header/__snapshots__/header.test.js.snap#L407-L414 https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/kuma/javascript/src/header/main-menu.jsx#L131-L135 https://github.com/mozilla/kuma/blob/a1c30da6316e54c829af82f3a06cc400d874412a/tests/pages/base.py#L91

</details>

**Comment by ankiiitraj** [comment]
I am sorry @schalkneethling, I found my PC hardware requirements not sufficient for Docker to be operated. Can you suggest me an alternative way of solving the issue.

**Comment by schalkneethling** [comment]
Hey @ankiiitraj,

No worries lets try another approach. With the repository cloned on your machine, go ahead and create a feature branch(ensure you have the latest from master before creating the new branch), like so: `git checkout -b issue#5647-change-report-a-bug-to-point-to-github`

Next, have a look at all of the instances mentioned by @ExE-Boss here https://github.com/mozilla/kuma/issues/5647#issuecomment-522613077 and update the URL from `https://bugzilla.mozilla.org/form.mdn` to `https://github.com/mozilla/kuma/issues/new`

Also, where the text label reads `Report a bug`, let's change that to `Report an issue`.

Once you have done that, please open a pull request and assign me as the reviewer. I will then review and test the code, and we can take it from there.

Please let me know if any of the above is unclear.
