### ISSUE TITLE
Full URLs in search results make it difficult to read

### ISSUE THREAD

**Issue by callahad** [mozilla/kuma#5658]
Right now our search results take the form:

> __Title__
> *https://developer.mozilla.org/en-US/docs/Example*
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
> *...Duis aute irure __dolor__ in reprehenderit in voluptate velit...*
> *...esse __cillum__ dolore eu fugiat nulla pariatur. Excepteur sint...*
> *...occaecat cupidatat non __proident__, sunt in culpa qui officia...*

For whatever reason, I find the long, full URLs to be distracting and difficult to read. Especially since the first 41 characters (`https://developer.mozilla.org/en-US/docs/`) are the same for every result.

I suggest we abbreviate the URLs to emphasize just the document slug (e.g., `/Web/API/WebRTC_API`, the only part of the URL that varies between results.

Comparison screenshot:

![Full URL versus Document Slug](https://user-images.githubusercontent.com/24193/63334546-8d20db80-c333-11e9-91a1-0dd1013a2616.png)

Our options are:

1. Full URL *(status quo):*
    `https://beta.developer.mozilla.org/en-US/docs/Web/API/WebRTC_API`

2. Schemaless URL:
    `beta.developer.mozilla.org/en-US/docs/Web/API/WebRTC_API`

3. Absolute Path:
    `/en-US/docs/Web/API/WebRTC_API`

4. Slug Only:
    `/Web/API/WebRTC_API`

In all cases, the patch is a completely trivial modification to [search-results-page.jsx](https://github.com/mozilla/kuma/blob/d51048f1a8c5a608266fd798a7643f462acb42cc/kuma/javascript/src/search-results-page.jsx#L108).

**Comment by callahad** [comment]
cc: @atopal @peterbe Per our chat yesterday

**Comment by ruchikabgosain** [comment]
Hello @callahad, is this a good first bug? I would love to contribute to this repository. ✨

**Comment by peterbe** [comment]
> is this a good first bug? I would love to contribute to this repository. ✨

No it's not. @callahad Already made [a PR](https://github.com/mozilla/kuma/pull/5657) but it just wasn't marked so it would tie to this issue.

**Comment by peterbe** [comment]
@ruchikabgosain Unfortunately we don't have a lot of good first bugs. The easier ones are hard to come by as they tend to get done and disappear as quickly. 
What we really need help with is reviewing PRs. It's genuinely helpful. Both for spotting obvious mistakes but also, and most importantly, to download the branch, run it locally and verify that it works. At the time of writing, we have [28 open pull requests](https://github.com/mozilla/kuma/pulls) and it's growing. Core contributors (i.e. members of Mozilla staff on the team) will do the final approval and merge but it would be amazingly useful if a contributor can help out simply by saying "I downloaded it and ran it and yes, the button click now works and it's sparkly pink like mention in the issue"

**Comment by ruchikabgosain** [comment]
hey, @peterbe I understand and I would love to review them, let me know how can I help with that :)

**Comment by peterbe** [comment]
Another option is to display it as a breadcrumb actually. On https://beta.developer.mozilla.org/en-US/docs/Glossary/WebRTC for example it looks like this:
<img width="526" alt="Screen Shot 2019-09-17 at 12 41 36 PM" src="https://user-images.githubusercontent.com/26739/65061727-885a4200-d948-11e9-8fed-71e3f5620cd1.png">
Although, I guess we'd need to make the last word clickable. 

But I'm not sure I have a strong preference for any of them. My favorite is number 3, "Absolute Path:"

I suggest that we punt on this one until the time has come to invest a little bit of UX love into site-search.

**Comment by callahad** [comment]
...I'm not convinced that #5770 fixed this -- the URL display seems mostly unchanged :)

> ![Screenshot of status quo, showing full URLs in search results](https://user-images.githubusercontent.com/24193/65779175-39c65800-e13f-11e9-902b-0fe4358de4cb.png)

Breadcrumbs would likely be preferable, but for now just rendering the document slug instead of the full URL seems preferable:

> ![Screenshot of proposed modification](https://user-images.githubusercontent.com/24193/65779427-a5102a00-e13f-11e9-8e3b-dc81f5d38e9e.png)

The patch is trivial:

```patch
diff --git a/kuma/javascript/src/search-results-page.jsx b/kuma/javascript/src/search-results-page.jsx
index 0c72a9231..e97700c95 100644
--- a/kuma/javascript/src/search-results-page.jsx
+++ b/kuma/javascript/src/search-results-page.jsx
@@ -100,8 +100,6 @@ export default function SearchResultsPage({ locale, query, data }: Props) {
 
             resultsNode = (results.documents || []).map(result => {
                 let path = `/${locale}/docs/${result.slug}`;
-                let url =
-                    window && window.origin ? `${window.origin}${path}` : path;
                 return (
                     <div className="result-container" key={result.slug}>
                         <div className="result">
@@ -117,7 +115,7 @@ export default function SearchResultsPage({ locale, query, data }: Props) {
                                 }}
                             />
                             <div className="result-url">
-                                <a href={path}>{url}</a>
+                                <a href={path}>{result.slug}</a>
                             </div>
                         </div>
                     </div>
```

**Comment by peterbe** [comment]
For the record, it was a mistake that the PR closed this issue. It was not my intention. A fumble.

**Comment by peterbe** [comment]
Can we just ask Nick which formatting is best and just take his recommendation? I'm not sure I care enough but I have a slight preference for your latest suggestion of just taking the `result.slug` instead.

**Comment by peterbe** [comment]
Actually, if you go ahead and make that patch I'll approve it. Better than having to see the domain on every single line when it's never different.

**Comment by atopal** [comment]
Yes, please go ahead with that.

**Comment by callahad** [comment]
This was fixed as part of https://github.com/mozilla/kuma/pull/5899
