### ISSUE TITLE
Ensure user signup page uses new UI design

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5660]
While working on the first iteration of the new sign-up flow I realized that it will currently still use the "old" layout/design. When stepping through the workflow it feels unsettling to me to start on this page:

![Screenshot 2019-08-20 at 16 10 53](https://user-images.githubusercontent.com/10350960/63354922-97f46400-c365-11e9-9bdb-555403d82056.png)

then be directed to Github

![Screenshot 2019-08-20 at 16 12 01](https://user-images.githubusercontent.com/10350960/63354956-a773ad00-c365-11e9-8e88-effd791c111c.png)

And then end up on this page:

![Screenshot 2019-08-20 at 16 12 20](https://user-images.githubusercontent.com/10350960/63354978-b0fd1500-c365-11e9-855a-17b17128fa44.png)

I, therefore, suggest that we update the sign-up page to use the same base template as the homepage(which will give us the new header), and then also ensure that the page content matches the new design from @nickbrandt 

Thoughts @atopal @peterbe @callahad @nickbrandt

**Comment by peterbe** [comment]
I'm not sure what your question is @schalkneethling but the callback page should take you to the React site, not the wiki site. If that doesn't work, we have to figure that out. 

What's not clear, to me, is that if you're deliberately on the wiki and sign in (for the first time ever!) what should it redirect to? The React site or the Wiki? Perhaps it doesn't matter if we smartly re-use the same jinja functionality all in one place.

**Comment by schalkneethling** [comment]
> I'm not sure what your question is @schalkneethling but the callback page should take you to the React site, not the wiki site. If that doesn't work, we have to figure that out.

Oh, it does not redirect to `wiki.` but, because we are merely skinning the existing sign-up page, it currently still uses the old design so, it looks like you are on wiki. My suggestion, therefore, is to go with a hybrid, like we currently do on the homepage.

A hybrid approach because:

1. We get to the new flow quicker as we do not have to redo everything on the page in React
2. We bring in the new style header, the footer has not changed, and so the bulk of the work is updating the layout and styling for the page content to match our new evolving design/layout.

**Comment by schalkneethling** [comment]
> What's not clear, to me, is that if you're deliberately on the wiki and sign in (for the first time ever!) what should it redirect to?

That is a very good question indeed.

**Comment by atopal** [comment]
If it's a big win in terms of time, I'd go with the hybrid, otherwise, we might as well take the time to do it in react, since that's where we're heading anyway.

I think the wiki interface is for editing/managing content only. Everything else should be on the react page, so clicking on log-in should redirect you to this new flow.
