### ISSUE TITLE
Audit React code for excessive re-renders

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5670]
In recent weeks, when poking at the React code for various things I've noticed that sometimes things get unnecessarily re-rendered. I think. React has a virtual DOM to protect the DOM even when components re-render. But Excessive re-renders are detrimental to performance. Especially if they're "large scale".

This issue is initially about doing an audit and figuring out if there *are* glaring mistakes that cause excessive re-renders that *can* be optimized away.

**Comment by Gregoor** [comment]
Okay, I didn't get my fauly asset serving problem solved. Instead I just went with heavier caching. Horrible for development, good enough for inspecting. Anyway:

For `article.jsx` the second render comes from the router, the third from UserContext. Overall the additional renders occupy ~2ms for the Article-Component on my machine (unfortunately couldn't throttle CPU while profiling, as that led to the asset issue again).

Since we're not using client-side routing anyway I could look into ripping that out. I guess the only thing that'd remain is Google Analytics. That would supposedly shave 4ms off on my machine (should be at least a couple of frames saved on a low powered device).

**Comment by peterbe** [comment]
I still don't know or understand why the `document` prop in component `Article` appears as a DivElement in my Web Console. (...and not just a plain object). 

Either way, if you if I skimm through the code for the `Article` component, it seems the virtual DOM saves us from, the more pressing problem: excessive DOM mutations. 
However, I can't figure out how `dangerouslySetInnerHTML` works. Does it work with the virtual DOM? I.e. does trigger any real DOM operations if rendered twice with the same `__html` string?
I tried googiing for an answer but failed. Everyone's just talking about the "danger" of `dangerouslySetInnerHTML` rather than how it works. But my gut tells me that it's safe to re-rendering with the same string without it having to mutate the DOM.

**Comment by peterbe** [comment]
Perhaps, one crazy idea to measure this is to have an effect on `Article` that mutates the some simple local state 100 times in a `setInterval`. If the virtual DOM was NOT protecting us the page would make your browser tremble in sweat. E.g.
```javascript
const [number, setNumber] = useState(0)
useEffect(() => {
  const loop = setInterval(() => {
    if (number > 100) clearInterval(loop)
    else setNumber(number + 1)
  }, 10);
}, []);
```

**Comment by Gregoor** [comment]
> I still don't know or understand why the document prop in component Article appears as a DivElement in my Web Console. (...and not just a plain object).

Strange indeed, in my console it's a regular ol' object:
![Screenshot (1)](https://user-images.githubusercontent.com/4051932/64418372-2c1b3680-d09b-11e9-9937-0e79690d1678.png)

> However, I can't figure out how `dangerouslySetInnerHTML` works. Does it work with the virtual DOM? 
Yes, it mostly behaves like any other prop, i.e. on rerenders the tree returned by a component is compared for differences with the previously rendered tree. If prop has changed different things could happen, depending on the element type and prop: In the case of a DOM-element it might lead to ReactDOM calling `setAttribute`. For `dangerouslySetInnerHTML` it'd call `.innerHtml = ?` on the respective element.
I did some writing about my understanding on how React's diffing works last year: https://dflate.io/svelte-react-reconciliation#%EF%B8%8F-react
