### ISSUE TITLE
Remove @Emotion

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5685]
We are seeing more and more potential long term maintenance problems with using Emotion in the way we currently do. It currently also complicates local development with server-side rendering to some extent but more importantly, the code that is generated adds a *lot* of bloat to our HTML via inlined `style` tags, sometimes as many as ~220.

There might be(there possibly is) ways to improve this but, the effort to investigate this does not seem to justify the end goal. Having all our CSS in CSS[read Sass] just makes a lot more sense.

With that, it is time to remove Emotion in favor of Sass.

**Comment by schalkneethling** [comment]
We can get there but, this is an important first step. I would love to get to the point where we can `import` Sass as we import SVG at the moment. Then we can have Webpack handle compiling and splitting that all up and use the `MiniCssExtractPlugin` https://webpack.js.org/plugins/mini-css-extract-plugin/ to do all kinds of cool stuff, like inlining everything if the file is below x.kb etc.

Some of that still depends on us also having moved away from Jinja templates to some degree, but still, currently, I do not feel that Emotion is providing any benefit.

**Comment by Gregoor** [comment]
Was about to mention scoping as a benefit of emotion (i.e. not accidently reusing selector names), but it looks like css-loader can take care of that as well:
https://github.com/webpack-contrib/css-loader#scope
Neat!
