### ISSUE TITLE
Simplify display of contributors per page

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5717]
To quote @atopal [from here](https://github.com/mozilla/kuma/issues/5669#issuecomment-525685343)

> let's just replace the whole section with "last edited on xx by MDN contributors" and that links to the revision history. If someone can come up with a good use case for having the full list on the article page itself, we should consider that, but nothing comes to mind.

@chrisdavidmills Are you OK with that?

**Comment by chrisdavidmills** [comment]
For the record, yes, I'm OK with trying this.

**Comment by atopal** [comment]
Okay, let's go ahead with this one
