### ISSUE TITLE
Revert beta feedback notice

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5722]
We have the little yellow flap in the upper right-hand corner. 
**This needs to disappear before we launch!!**

The original instructions said to revert a certain pull request: https://github.com/mozilla/kuma/blob/2490ae8b85d9d3a65602ecf60756af337e0ce2d9/kuma/javascript/src/header/header.jsx#L36
That might not work yet. 

Also, in https://github.com/mozilla/kuma/pull/5703 @schalkneethling is refactoring the beta notice's Emotion for SCSS.

**Comment by escattone** [comment]
Just FYI, I do remove the little beta feedback notice in the upper left corner within https://github.com/mozilla/kuma/pull/5639.

**Comment by peterbe** [comment]
@escattone As mentioned in some other comment or email. Be prepared to rebase because I think @schalkneethling wants to eliminate all Emotion first. And he can only accomplish that if he tackles the beta feedback notice widget too. But my suggestion was to just delete it here and now rather than converting it from Emotion to SCSS.

**Comment by schalkneethling** [comment]
As mentioned via email:

> I think that makes sense. We are getting ready to switch, not getting ready for more beta testing. Removing.
