### ISSUE TITLE
Site-search CSS busted

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5750]
Screenshot says it all...

<img width="1680" alt="Screen Shot 2019-09-04 at 3 20 45 PM" src="https://user-images.githubusercontent.com/26739/64284462-a7f47200-cf27-11e9-81bb-31f82a4fd363.png">

**Comment by schalkneethling** [comment]
@peterbe Did you hook up the new CSS? https://github.com/mozilla/kuma/blob/master/kuma/static/styles/minimalist/structure/_search-results.scss

Also, I believe I made some changes to the classes, but those probably made their way across when you rebased against master. Let me know if the above does not resolve the problem.

**Comment by schalkneethling** [comment]
So, you can either add `_search-results.scss` to its own main `search-page.scss` file and then create a custom bundle inside `common.py` for the search results page or, you can include it in `minimalist/document.scss` if that works for now.

**Comment by peterbe** [comment]
> Did you hook up the new CSS?

I haven't touched any of that :)
Also, my work on site-search is only in a branch on my laptop. Would you mind assigning this one to yourself?
