### ISSUE TITLE
Delete localizations with less than 10 page views per day

### ISSUE THREAD

**Issue by tobinmori** [mozilla/kuma#5788]
https://bugzilla.mozilla.org/show_bug.cgi?id=1469079

https://bugzilla.mozilla.org/show_bug.cgi?id=1483763

https://bugzilla.mozilla.org/show_bug.cgi?id=1528618

**Comment by escattone** [comment]
FYI, for these 28 locales that I've removed, I've also removed them from https://github.com/mozilla-l10n/mdn-l10n (see https://github.com/mozilla-l10n/mdn-l10n/commit/b07c9e901befc7ea463d0e30d1fcc42f34730708) as well as archived those locales within Pontoon (i.e., put them into read-only mode).

**Comment by escattone** [comment]
I also added final comments and closed the following Bugzilla issues:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1425357
- https://bugzilla.mozilla.org/show_bug.cgi?id=1528618
- https://bugzilla.mozilla.org/show_bug.cgi?id=1469079
- https://bugzilla.mozilla.org/show_bug.cgi?id=1483763

**Comment by SphinxKnight** [comment]
Thanks @escattone 👏 :)
