### ISSUE TITLE
New frontend: no call to action for missing translation

### ISSUE THREAD

**Issue by SphinxKnight** [mozilla/kuma#5806]
Previously, when a user landed on `https://developer.mozilla.org/<localeX>/slug/` because they clicked on a link using `https://developer.mozilla.org/slug` (this is supposed to redirect to the user's locale), a call to action was displayed to help with the translation.

Steps to reproduce:
* Ran the accessibility controls from the Fx devtools
* Clicked on a link : https://developer.mozilla.org/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast 
* Was redirected to https://developer.mozilla.org/fr/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast

Previous/expected result:
* a CTA box as displayed in https://wiki.developer.mozilla.org/fr/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast
![image](https://user-images.githubusercontent.com/2413436/64759187-bc8fc600-d536-11e9-9bec-6b6ce46723bf.png)

Current result:
* No indication that I'm reading the en-US content though the URL contains the /fr/ fragment on https://developer.mozilla.org/fr/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast
![image](https://user-images.githubusercontent.com/2413436/64759299-08db0600-d537-11e9-9cc6-314ec9865cd3.png)

Aside:
I know that localization may be not the strongest point of MDN (both content and tooling/feature wise) at the moment but that's not helping getting traction here.

**Comment by SphinxKnight** [comment]
cf. https://github.com/mozilla/kuma/blob/558716f5efa0a8efc085f03e4cf0d96b1591081e/kuma/wiki/jinja2/wiki/document.html#L204-L226

**Comment by SphinxKnight** [comment]
a "minimal" version of it could be a fair warning "you're reading the English version of the content".

**Comment by atopal** [comment]
Yeah, this was not an intended change of UX, it's a regression.

**Comment by peterbe** [comment]
> a "minimal" version of it could be a fair warning "you're reading the English version of the content".

If we're going to figure out when/how to write that message we might as well invest in the proper message as described in this issue. 

Thanks for filing!

**Comment by atopal** [comment]
To be clear: this is a regression. We had no intention to change the behavior and the goal is to restore the previous UX. No need for new messaging.
