### ISSUE TITLE
New frontend: empty page for /search route (no redirect / no 404)

### ISSUE THREAD

**Issue by SphinxKnight** [mozilla/kuma#5808]
Steps to reproduce:
* Went to https://developer.mozilla.org/en-US/search

Current result:
* A semi blank page with the footer of the site

Expected result:
* A redirect to https://wiki.developer.mozilla.org/en-US/search or a 404

**Comment by peterbe** [comment]
Note-to-self; My solution in https://github.com/mozilla/kuma/pull/5770 claims to fix this issue. 
If you go to https://wiki.developer.mozilla.org/en-US/search it appears to make a search for every single en-US document. It's not horribly broken so I think that problem can wait.
