### ISSUE TITLE
blocked localStorage breaks site

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5815]
This came from: https://bugzilla.mozilla.org/show_bug.cgi?id=1580915

<img width="1319" alt="Screen Shot 2019-09-12 at 4 28 23 PM" src="https://user-images.githubusercontent.com/26739/64818613-6ba1c100-d57a-11e9-9bd3-4a71d564df0b.png">

How I reproduced it:
<img width="1319" alt="Screen Shot 2019-09-12 at 4 29 21 PM" src="https://user-images.githubusercontent.com/26739/64818662-83794500-d57a-11e9-92a0-8fdb81cb367b.png">

**Comment by Gregoor** [comment]
Clearly I was lacking imagination 🙈 
https://github.com/mozilla/kuma/pull/5765#discussion_r322157041

**Comment by peterbe** [comment]
@tobin why did you reopen this? There is no more work to do.

**Comment by peterbe** [comment]
The problem belong(ed) to me as an issue. Then, it became a PR and that belong(ed) to Gregoor. 

We can think of GitHub PR review request as a form of notification and PR assignment as a hack to make the Zenhub board work for us. 

So, the flaws are:

1. PRs don't appear as cards on the board (in the right swim lane) simply by the review request
2. Closed Issues *and* PRs don't move to the Done lane. 

Current solutions:

1. We manually remember to assign as well as request reviewer. 
2. We manually drag the cards over. 

Future solutions:

We hire a cadre of monkeys to write Heroku/Glitch scripts that take away our jobs from the "Current solutions" section.

**Comment by tobinmori** [comment]
Indeed. this is one of my gripes with Zenhub. The Jira world (never thought I'd lament missing Jira!) has subtickets which attach work to an issue (and keep them tightly coupled). 

One of my goals will be to automate all these problems away (eventually). . .

But for now you're right - we need to explicitly assign Reviewers as Assignees and do draggin' :(
