### ISSUE TITLE
Server-side generate site-search

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5824]
Originally from: https://bugzilla.mozilla.org/show_bug.cgi?id=1567487

The site-search page is slow because it depends on first downloading a "blank skeleton", then downloading the React bundle, and then React can paint `<h3>Results: {searchTerm}</h3>` whilst it waits for the actual XHR to do the fetch. 

![Screen-Recording-2019-09-13-at-12 09 03-PM](https://user-images.githubusercontent.com/26739/64877776-0d2f1e00-d620-11e9-8ac5-cb35124a812b.gif)

**Comment by peterbe** [comment]
@joedarc Is this something you think you can take a look at?

**Comment by joedarc** [comment]
@peterbe Yeah, I'll try and take a look at this over the weekend. 👍

**Comment by joedarc** [comment]
@peterbe I have a version of this working locally, however it looks like i need to rebase. Some changes were made recently that'll affect what i did, but it shouldn't require too many changes on my end.
