### ISSUE TITLE
Redirect Firefox-specific WebExtensions docs to Extension Workshop 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/kuma#5841]
The Firefox Add-ons team has created [Extension Workshop](https://extensionworkshop.com), a site for extension developers to quickly find information related to developing Firefox Extensions. To make sure developers find the most current information, we need to redirect those pages on MDN to point to Extension Workshop. 

The list of affected pages can be found on this [spreadsheet](https://docs.google.com/spreadsheets/d/15XxPb3mgnvOjWYqcySQMiBAdfsgfEJ5RHx_B5YPTaKI/edit#gid=1796998978). 

MDN pages that are redirected should also be updated to replace existing content with a brief message that the content can be found on Extension Workshop. 

**Due Date**
It would be great if the stage-to-stage test could be run by Wednesday, September 18 to give EW QA time to flag any issues. **edited to change date to September 18 at 9:13am PST**

October 1 is EW's intended "go live" date. Once the prod site is turned on, we would ask that the redirects be implemented on MDN prod. 

**Additional context**
For additional context, here's EW's [pre-flight checklist](https://docs.google.com/document/d/1BrWkiWFe5nysxEd14Vdb9jMhw8VYUKrMbYrPnRN27L0/edit#). 

/ cc @muffinresearch

**Comment by escattone** [comment]
@caitmuenster This ready for your testing on MDN stage (https://developer.allizom.org). For example, https://developer.allizom.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Security_best_practices redirects to https://extensionworkshop-dev.allizom.org/documentation/develop/build-a-secure-extension/.

NOTE: None of the documents have been modified on stage. We'll do that only after this goes to production with the production redirects.

cc @tobinmori

**Comment by caitmuenster** [comment]
Thank you @escattone!

**Comment by escattone** [comment]
@caitmuenster Just FYI, I'll be pushing new code to our stage/production instances later today (in about 3-4 hours from now). I just wanted to let you know since it will over-write the changes I pushed to our stage instance for your stage-to-stage testing. I can re-deploy those changes again tomorrow if you were not able to run your tests yesterday. If you were able to run your tests yesterday, did our changes look good to you? If so, I'll finalize a PR for production as well.

**Comment by caitmuenster** [comment]
Hey @escattone! I took a look and it seemed ok but I haven't gotten the final sign off from QA yet. 

Could you re-deploy these changes tomorrow? 

Thanks so much! 

/ cc @vcarciu

**Comment by escattone** [comment]
@caitmuenster Just FYI, I re-deployed my redirect changes to stage, so you're good for QA tomorrow!

**Comment by caitmuenster** [comment]
Hey @escattone, it looks like the redirects worked well and we should run the script on prod next week. 

We would still like to keep those pages on MDN, but replace the content of the page with a short message saying, "This page has moved to [new URL]. If you are not automatically redirected, please click on that link." 

Is that possible to do via the script? If not, I can update the text on those pages manually.

**Comment by escattone** [comment]
@caitmuenster Thanks for the update, and next week works fine for us. When will your documents be ready on https://extensionworkshop.com? I want to make sure we don't merge and deploy https://github.com/mozilla/kuma/pull/5876 until you're ready for the redirects.

Although the MDN documents won't be reachable once https://github.com/mozilla/kuma/pull/5876 is merged and deployed, I can still go ahead and update the documents automatically via a script.

**Comment by caitmuenster** [comment]
@escattone Got it! Assuming things go according to plan (😉), documents should go live on extensionworkshop.com on Tuesday, October 1 before 10am PST. I can confirm with you once they're up. 

It would be great to update the content of those pages before the redirects are merged and deployed. Thank you!

**Comment by caitmuenster** [comment]
Hi @escattone, Extension Workshop is now live on [prod](https://extensionworkshop.com)! We're good to deploy the redirects.

**Comment by escattone** [comment]
@caitmuenster This has been deployed to production and looks good from the few links I've tried!
