### ISSUE TITLE
Expose the GitHub avatar to Jinja as well as via the "whoami" endpoint

### ISSUE THREAD

**Issue by escattone** [mozilla/kuma#5848]
**Summary**
Expose the GitHub avatar to the front-end code as both a Jinja helper as well as an attribute of the `whomai` endpoint.

**Rationale**
Required as part of #5830 

**Audience**
All MDN members

**Comment by peterbe** [comment]
I don't think this is right. If https://github.com/mozilla/kuma/issues/5830 needs the gravatar URLs in the jinja rendering it should just do so. Exclusively for that relevant view. There's already a jinja helper function in `kuma/users/templatetags/jinja_helpers.py` so if you need the gravatar you simply call `<img src="{{ gravatar_url(edit_user.email, size=200) }}">` or something in the jinja template.

**Comment by escattone** [comment]
> I don't think this is right. If #5830 needs the gravatar URLs in the jinja rendering it should just do so. Exclusively for that relevant view. There's already a jinja helper function in `kuma/users/templatetags/jinja_helpers.py` so if you need the gravatar you simply call `<img src="{{ gravatar_url(edit_user.email, size=200) }}">` or something in the jinja template.

Yes, but that's for the gravatar URL (the `whoami` endpoint already provides that as well). My understanding is that @schalkneethling needs the user's avatar from GitHub, which we don't yet provide for either case.

**Comment by schalkneethling** [comment]
> > I don't think this is right. If #5830 needs the gravatar URLs in the jinja rendering it should just do so. Exclusively for that relevant view. There's already a jinja helper function in `kuma/users/templatetags/jinja_helpers.py` so if you need the gravatar you simply call `<img src="{{ gravatar_url(edit_user.email, size=200) }}">` or something in the jinja template.
> 
> Yes, but that's for the gravatar URL (the `whoami` endpoint already provides that as well). My understanding is that @schalkneethling needs the user's avatar from GitHub, which we don't yet provide for either case.

Correct, we should be using the avatar from Github when a user authenticates with Github. Which is currently the only way, but that will change in the future.

**Comment by peterbe** [comment]
/me an idiot. 
I must have read that too quickly. Sorry.

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/5871

**Comment by elham9066** [comment]
Yy

۱۳۹۸-۰۷-۰۲ ۱۷:۵۹ ‎−۰۷:۰۰ گرینویچ, Ryan Johnson <notifications@github.com>:
