### ISSUE TITLE
Asking to confirm old email

### ISSUE THREAD

**Issue by LeetCodes** [mozilla/kuma#5852]
When I click sign in on MDN, I'm redirected to a page asking me to confirm my email address, but the confirmation is sent to a very old email address that I don't even have on my github account anymore and haven't for almost a year. The domain is no longer owned by me and I have no way of accessing mail sent to it. Not sure if I signed in with my github in the past when it was still associated with my account, but I don't see anyway to resolve the issue myself.

**Comment by escattone** [comment]
@LeetCodes I changed your MDN email to match your GitHub email.
