### ISSUE TITLE
Improve Sass build tooling

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5860]
**Summary**

Local development for the new front end has improved a lot but the Sass portion has lagged behind. This can and does cause friction for both pull request review and general front-end development.

**Audience**
All developers contributing to the codebase.

**Rationale**

I, for one, regularly have to run the entire `docker-compose exec web make build-static` when making changes to the Sass files. This is slow and often leads to Docker slowing down to a crawl.

We do have a Gulp task but it has become very unreliable.

**Workaround**
As described in rationale

**Proposal**
Simplify how we build our CSS from Sass by using `node-sass-chokidar` directly instead of via yet another build tool. There are also some changes we can make to the "old" Sass source to make better use of Sass partials.

**Comment by peterbe** [comment]
I see no mention of `npm run` in https://kuma.readthedocs.io/en/latest/development.html
Only on Slack. Should we reopen this issue until the docs have been updated?

**Comment by schalkneethling** [comment]
> I see no mention of `npm run` in https://kuma.readthedocs.io/en/latest/development.html
> Only on Slack. Should we reopen this issue until the docs have been updated?

I think it is ok to leave this one closed. I do need to update the docs for more than just the latest round off changes so, let me open a separate issue for that. Thanks, Peter.
