### ISSUE TITLE
Missing description for creating entity

### ISSUE THREAD

**Issue by tamtm** [mozilla/kuma#5912]
Expected a method includes create a new entity, but there is no description mention it.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by schalkneethling** [comment]
> Expected a method includes create a new entity, but there is no description mention it.
> [developer.mozilla.org/en-US/docs/Web/HTTP/Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)

Thank you for reporting this @tamtm - I believe this is a content issues that is handled by the writers. These issues are logged in the following repository:
https://github.com/mdn/sprints/issues/

@chrisdavidmills ping

**Comment by chrisdavidmills** [comment]
I've created an appropriate issue over on our content sprints repo. Thanks @tamtm !
