### ISSUE TITLE
Remove wiki/reviews.scss from minimalist/document.scss

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5920]
Currently we include `kuma/static/styles/components/wiki/reviews.scss` inside `kuma/static/styles/minimalist/document.scss`. From the comment inside `reviews.scss` this is styling for the document review form, and is such, is not part of the new frontend.

## Potential saving

+--------------------------------------------------------------+
| Size         | 648 bytes                                     |
|--------------------------------------------------------------|
| Gzipped      | 298 bytes                                     |
|--------------------------------------------------------------|

**Comment by Gregoor** [comment]
Oh forgot to tag this one in #5933. Done!
