### ISSUE TITLE
Internal Server Error occurs when some chapters are translated into Chinese

### ISSUE THREAD

**Issue by muling800** [mozilla/kuma#5940]
When I follow the usual steps to publish the translated content, it prompts me for an internal error :

For example: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors$translate?tolocale=zh-CN

**Any changes will occur the following error:**

Internal Server Error
An unhandled error occurred in the application. The error has been logged and an administrator was notified. We apologize for the inconvenience!

**Comment by tobinmori** [comment]
Apologies, our database, as it's currently set up, does not support 4 byte encoding. 

We will open up an issue to investigate updating our db and migrating the data to support UTF-8mb4.

**Comment by tobinmori** [comment]
This issue has been added to our backlog:
Upgrade MySQL to support UTF-8mb4#5942

**Comment by muling800** [comment]
Thank you for your reply
