### ISSUE TITLE
Why does the developer console not start on old firefox versions?

### ISSUE THREAD

**Issue by Eddcapone** [mozilla/kuma#5946]
I installed some old firefox versions from [v44](https://ftp.mozilla.org/pub/firefox/releases/44.0/win64/de/) to v46 because there is a cool 3D View feature (See issue #5945 ) which was removed since v47, and noticed that the developer console does not start. 

Does firefox intentionally disable it on older versions in the archive?

**Comment by peterbe** [comment]
Please use: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Console
