### ISSUE TITLE
MDN system no longer sending me e-mail notifications for articles/trees I watch

### ISSUE THREAD

**Issue by sideshowbarker** [mozilla/kuma#5947]
My MDN account is at https://developer.mozilla.org/en-US/profiles/sideshowbarker. I have a number of watches set up for several article trees and individual articles. But on July 27th, I stopped receiving any e-mail notifications for those watches.

Prior to that, I was receiving about 15 to 20 e-mail notifications each day.

Today I tried changing my e-mail address in the system — to see if that made any difference — but I’ve still not received any new notifications.

**Comment by escattone** [comment]
@sideshowbarker Thanks for the update! I'll close this, but of course you can re-open this if you discover something is amiss.
