### ISSUE TITLE
Expose the "raw Kuma HTML" in the Document JSON API

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5949]
The Document JSON API only contains some meta data, the `tocHTML`, the `quickLinksHTML`, and the `bodyHTML`. If you want to find out, to "reverse engineer", **how KS macros were called** you have to  `GET {FULL_DOCUMENT_URL}?raw`. This won't scale if you need to try to convert thousands of documents to static files to put pushed through the static site generation stuff in Stumptown for example.

**Comment by peterbe** [comment]
I propose we add a new field like `kuma_html` to `kuma.api.v1.views.document_api_data`'s response. 

If we had that, since those are published to an S3 bucket we'd be able to do an S3 batch operation to download N documents and extract the rendered HTML *and* figure out what the HTML became AND what various arguments were when calling `{{Compat(.*?)}}`.

**Comment by escattone** [comment]
@peterbe Would it be at least equally helpful (maybe even more helpful) to include a list of all of the macro calls and their arguments, rather than the entire raw document? I'm wondering if it might be worthwhile to explore that path in order to reduce the amount of duplication in the data. Or maybe for reverse-engineering purposes it's really helpful to have the macros "in situ"?

**Comment by peterbe** [comment]
All excellent points @escattone and I think it's worth slowing down to carefully test what's needed and what works. I already implemented what this issue says, in a branch, and I now have an S3 bucket full of JSON documents that have the rendered HTML and the raw HTML so with that I *should* be able to produce an auxiliary file structure that I can send through the stumptown pipes. 

This is my skunkworks project and it's nowhere near going into `master` :)

But having this issue will help as a dumping ground for ideas and notes.

**Comment by wbamberg** [comment]
FWIW I've been doing something similar, to scrape Wiki pages for stumptown. For this, most macro calls I will simply remove (by taking the "?raw&macros" and converting to Markdown). But there are some - only `Compat`, `EmbedLiveSample`, `EmbedInteractiveSample` at the moment - that I want to convert into something stumptowny.

And for that I've been using "?raw" to get the version with the macro calls in, then trying to extract macro calls and arguments out of that, then using "?raw&macros" as the source to scrape. So for this (which I think is close to what Peter is doing), yes, definitely, getting direct access to KS calls would be helpful.

But I suppose exactly what we want here depends on exactly what we are trying to accomplish :).

**Comment by peterbe** [comment]
I've been thinking about it some more. But probably not enough. 

Just getting the docs down to disk is hard. I think the best idea is to write a program that more or less gets all the Document JSON API docs down to disk is a task on its own. Then, I think the `scrape-mdn.js` would need to be broken up. Instead of getting one URL at a time, it would get one local file at a time. Then, when running the stuff that `scrape-mdn.js` does it'll read slightly differently but it would also not attempt to say the output is perfect for inclusion into the stumptown-content git repo. Perhaps, next to the `content` directory there'd be a `legacy-content` directory which would look very similar. Next, we'd run `build-json` on *both* `content` and `legacy-content` with a hint to "prefer" the URLs from `content` if there's an overlap on the `mdn_url`. 

I.e. I'll worry about a way to get all the files onto disk from S3. Then I'll modify `scrape-mdn.js` to do what it does but read from disk and lastly output its results in a slightly different location. 

The idea is to do what Will does manually, except we do it in a super automated way, at large scale, and we don't check it into git when we're done instead we just pipe it to `build-json` or `stumptown-renderer` and upload the produced file back into some S3 bucket or something. All with the ability to do it all over again at the press of a button. 

`</loose-thoughts>`

**Comment by MatonAnthony** [comment]
Couldn't we just get a slave db and run a second Kuma in maintenance mode, then we could just use a celery task to write all documents to an S3 bundle?

If this doesn't sound totally stupid, I can expose my idea in more details.

**Comment by peterbe** [comment]
@MatonAnthony No need. Ryan and discussed this and the true solution lies elsewhere.
