### ISSUE TITLE
Strange footer article metadata display

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5954]
**Summary**
<img width="763" alt="Screen Shot 2019-10-09 at 1 55 56 PM" src="https://user-images.githubusercontent.com/26739/66507161-ab39cb00-ea9c-11e9-8ec0-95915bbc25ef.png">

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit https://developer.mozilla.org/en-US/docs/Games/Anatomy
2.  Scroll down
3. Read about when it was last modified

**Actual behavior**
_What actually happened?_

The HTML looks like this:

```html
<section class="contributors-sub">
  <svg class="icon icon-clock" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 28" aria-hidden="true"><path d="...."></path></svg>

  <header><h4>Last modified:</h4></header>

  <time datetime="2019-03-23T19:24:26.976056">Mar 23, 2019</time>,
  <a href="https://wiki.developer.mozilla.org/en-US/docs/Games/Anatomy$history" rel="nofollow">by MDN contributors</a></section>
```

**Expected behavior**
_What did you expect to happen?_
The `<header>` should probably not be used there. Nor the use if `<h4>`.

**Additional context**
_Is there anything else we should know?_

The new React site launched 5 min ago.

**Comment by peterbe** [comment]
The use of `<header>` was introduced 3 months ago. 
https://github.com/mozilla/kuma/commit/b0801bd05aeb5be02da78bbb74e56ad0325ef4f1

Strange that we didn't notice this strange whitespace until now. Perhaps recent refactoring of CSS caused this.

**Comment by ankiiitraj** [comment]
Can I help in solving this issue? Guide me in this please!

**Comment by schalkneethling** [comment]
Oh boy, I found this when I was working on https://github.com/mozilla/kuma/pull/5952, but I am more than happy to remove it from that PR and use @joedarc fix.

**Comment by schalkneethling** [comment]
> Can I help in solving this issue? Guide me in this please!

Someone else has grabbed this one already @ankiiitraj - I will keep an eye out for another issue and let you know.
