### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sites'

### ISSUE THREAD

**Issue by chxlvwh** [mozilla/kuma#5969]
**Summary**
_What is the problem?_
I was installing `Kuma` on my computer.
When I run the command `docker-compose exec web ./manage.py configure_github_social`, console desk show the Error `AttributeError: 'NoneType' object has no attribute 'sites'`.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Get in [https://kuma.readthedocs.io/en/latest/installation.html#load-the-sample-database](https://kuma.readthedocs.io/en/latest/installation.html#load-the-sample-database)
2. Find the step **Enable GitHub authentication (optional)**
3. At that step I run `docker-compose exec web ./manage.py configure_github_social`, and error occured.

**Actual behavior**
_What actually happened?_
I checked the code and found that in file `kuma/attachments/management/commands/configure_github_social.py` line 75, the variable `social_app` is None. Was I got something wrong?

**Comment by Gregoor** [comment]
Thanks for reporting this! Looks like I got confused with logical operators. PR is on the way.
