### ISSUE TITLE
WebRtc getUserMedia frameRate is not supported

### ISSUE THREAD

**Issue by 1312543912** [mozilla/kuma#5994]
Hello:
&nbsp;I called Firfox's webrtc api, and MDN showed support, but I made a mistake when I called it.
https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints  
https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia

### 1.webRtc getuserMedia frameRate:
    
![image](https://user-images.githubusercontent.com/21102828/66808336-94dcb500-ef5d-11e9-8efb-dfdd9f974d2f.png)
### 2.my code
```
  navigator.mediaDevices.getUserMedia({
      // audio: this.config.audio,
      video: {
        width: { min: 640, ideal: 1920 },
        height: { min: 400, ideal: 1080 },
        aspectRatio: { ideal: 1.7777777778 },
        frameRate: { max: 15},
      },
    }).then((stream) => {
      this.successCb(stream);
    })
```
### 3.error in firefox
![image](https://user-images.githubusercontent.com/21102828/66808445-d1a8ac00-ef5d-11e9-9474-6c2bb866f67e.png)

### UA
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0"

### other
When I wrote like this, he returned a dynamic bit rate.
```
    navigator.mediaDevices.getUserMedia({
      // audio: this.config.audio,
      video: {
        width: { min: 640, ideal: 1920 },
        height: { min: 400, ideal: 1080 },
        aspectRatio: { ideal: 1.7777777778 },
        frameRate: 15
      },
    }).then((stream) => {
      this.successCb(stream);
    })
```
I wonder why this happens？

**Comment by schalkneethling** [comment]
Thank you for getting in touch @1312543912 - I will ask our writers' team to have a look at this. cc @chrisdavidmills

**Comment by chrisdavidmills** [comment]
Resubmitted at https://github.com/mdn/sprints/issues/2250
