### ISSUE TITLE
Site should work even if you don't have window.fetch

### ISSUE THREAD

**Issue by peterbe** [mozilla/kuma#5995]
We're getting a lot of error boundaries happen because people's browser don't have `window.fetch`.

**Comment by peterbe** [comment]
Of about 2,000 errors...
<img width="877" alt="Screen Shot 2019-10-15 at 12 50 08 PM" src="https://user-images.githubusercontent.com/26739/66852184-5f7a9c00-ef4a-11e9-845d-3e7b3a1388b9.png">

About 400 are related to `fetch`
<img width="838" alt="Screen Shot 2019-10-15 at 12 49 32 PM" src="https://user-images.githubusercontent.com/26739/66852139-496cdb80-ef4a-11e9-8566-0148ca385a5f.png">

I.e. about 20%.

**Comment by peterbe** [comment]
Actually, we could do this:
```html
<script>window.fetch||document.write('<script src="https://unpkg.com/unfetch/polyfill"><\/script>')</script>
```
Then we don't need to add any code to our codebase. We also don't need to muck with existing code. 

The question still remains; how to test this?

**Comment by escattone** [comment]
@peterbe 👍 Nice, I like it!

**Comment by peterbe** [comment]
A concern is that if `fetch` doesn't exist, and we "fix" it with [`unfetch`](https://github.com/developit/unfetch) it will just proceed to the next problem. E.g. `Symbol` not being a function. 
So it might be pointless to fix `fetch` on its own because browsers that don't have `fetch` also don't have a bunch of other stuff.

**Comment by schalkneethling** [comment]
Which browsers present this problem? Do we perhaps have a list? Of course, lteIE10 will be part of this list, but are there other older versions of browsers? I know Firefox 38 was mentioned?

It feels to me like we should progressively enhance here instead of trying to support everything, everywhere. I believe the latest 3 versions of evergreen browsers are our A-grade browsers so, as of this writing ;)

Firefox 67, 68, 69
Chrome 75, 76, 77
Safari 12, 13
Edge 42, 44 (there seems to not have been a 43 ¯\_(ツ)_/¯)

### B grade browsers are IE10 and 11 and versions of modern browsers older than the above

This means that:

- All content must be accessible. (for us this might mean not hydrating on the client and serve little to no JS and only essential CSS(reader mode))
- Visual variations (e.g. rounded corners) are acceptable.

### C grade browsers are IE9 and lower:

- Key support content must be accessible. Other content and functionality may be hidden or disabled. (No JS, little to no CSS)
- Major visual variations allowed.

**Comment by atopal** [comment]
@schalkneethling that's more or less what Tobin and I talked about yesterday, and he's going to to codify that, so we can refer to it. I think your grades make a lot of sense, and for the items in them I have a few minor changes: 

For A grade: The latest 2 major versions are fine, beyond that some older versions actually have a higher share on MDN. Also, that would be for the desktop versions of Firefox, Chrome, Safari and Edge, and the mobile versions of Chrome, Safari and Firefox.

For Grade B: All IE versions makes up 1.3% of our traffic, IE11 is 91% of that, IE8 is 7%. So, I'd put IE 11 in B grade, but no other IE.

C grade would be everything else, and I'd say it's on a best effort basis.

**Comment by peterbe** [comment]
So, the scariest part is making the site work correctly in Edge 42 and Safari 12. Because those are so hard to test for the team. 

"Support" means two different things:

1. Work just like it does in your fancy Chrome or FirefoxNightly
2. Being able to consume the content and navigate the site

I think we're covered on point 1 right? Nothing needs to be done there.

On point 2, we're way behind. I dare to say that [this PR](https://github.com/mozilla/kuma/pull/5996) takes a huge bite out of that. What remains is more testing and injection of a "reader mode" CSS or whatever it's called. Right?

**Comment by schalkneethling** [comment]
I have thought about this some more, below is an update on my earlier comment(taking into account @atopal feedback) as well as a proposal for a good/decent/good-enough first step to a better experience for all users:

## Browser Matrix

### A Grade

Firefox 68, 69 (aka Latest and one version back)(Mobile and Desktop)
Chrome 76, 77 (aka Latest and one version back)(Mobile and Desktop)
Safari 12, 13 (aka Latest and one version back)(Mobile and Desktop)
Edge 42, 44 (aka Latest and one version back)(Mobile and Desktop)[This one is a little extra nuanced as it will soon essentially be Chrome)

### B Grade

Internet Explorer 11 and versions of modern browsers older than the above.

This means that:

- All content must be accessible. (for us this might mean not hydrating on the client and serve little to no JS and only essential CSS(reader mode))
- Visual variations (e.g. rounded corners) are acceptable.

### C Grade

- IE less the or equal to 10
- Versions of modern browsers that are 9 versions older than the latest. (This seems to roughly match up with what the latest ESR version of Firefox is. i.e. Firefox is at 69 and ESR is at 60.8.0)

This means that:

- Key support content must be accessible. Other content and functionality may be hidden or disabled. (No JS, little to no CSS)
- Major visual variations allowed.

## Proposal

MDN should be, and is for a large portion, coded with a mobile-first mental(read CSS) model. We can extend this idea further to help us better support the above browser matrix. 

Step one is to have a plain, simple, readable and usable mobile layout for MDN. This does not need to take advantage of any new modern layout techniques such as grid, flexbox etc. and can simply be coded as a stacked layout with a few small tweaks for usability.

We then have a progressively enhanced layout for small desktop(1024x768+) where we do take advantage of modern CSS but, we wrap this in `@supports` and `@media` queries. The use of `@supports` here is the key.

Any browser that does not understand `@supports`[1] will simply ignore everything inside these blocks and get the mobile layout(which we can dub `reader-mode`). 

[1] Combining `@supports` with `display: flex` as the feature means the following browsers will get the progressively enhanced layout:

- Firefox 28+
- Chrome 29+
- Safari and iOS Safari 9+
- Edge 12+
- No versions of Internet Explorer

That should be a major improvement in terms of the layout and style of MDN Web Docs.

## JavaScript

Versions of IE10 and lower should get no JS other than 1 small flavorless JavaScript file that makes the previously mentioned usability tweaks for the `reader-mode` layout. This will largely, perhaps even only, be to enable the current interaction we have with the main menu on mobile.

For the remainder, we should code defensively and never simply assume a feature will be available. We also currently have some logic to determine when to hydrate:

```
if (
    window.origin !== 'https://translate.googleusercontent.com' &&
    !isIE10 &&
    !isIE11
) {
    ReactDOM.hydrate(app, container);
}
```

We can do further research based on the data we are getting now that the new front-end is live and use this to further expand our conditional i.e. perhaps build a little utility function that returns the answer to the question `shouldHydrate`.

**Comment by atopal** [comment]
Sounds good to me Schalk, the only thing I don't quite understand is how things would look/work in IE11 with this proposal. Can you elaborate on that?

**Comment by schalkneethling** [comment]
> Sounds good to me Schalk, the only thing I don't quite understand is how things would look/work in IE11 with this proposal. Can you elaborate on that?

We already do not hydrate in IE11 and so for this first step, IE11 would get the reader-mode layout. Once all of the above has landed, we should explore how we can progressively enhance IE11 without causing a maintenance burden.

I have some ideas but, do not want to cognitively overload too much at this stage 😉

**Comment by atopal** [comment]
Schalk, is the proposed browser support matrix documented somewhere more permanent? Maybe it would be a good ADR candidate?

**Comment by schalkneethling** [comment]
> Schalk, is the proposed browser support matrix documented somewhere more permanent? Maybe it would be a good ADR candidate?

It will be part of our style guide/pattern library which lives on mdn-fiori.
